export const color = {
  inputBorder: "border-customOrange",
  placeholder: "placeholder-[#F4F4F4]",
  textWhite: "text-white",
  textInput: "text-[#F4F4F4]",
  bgColor: "bg-[#232020]",
  textVerified: "text-gray-500",
  textUnverified: "text-red-500",
  textSuccess: "text-green-500",
  textError: "text-red-500",
  defaultVibrantText: "text-vibrantSpectrumPrimary",
  defaultVibrantBorder: "border-vibrantSpectrumAccent",
  defaultVibrantBg: "bg-vibrantSpectrumBackground",
  forgetPassText: "text-[#232020]",
  forgetPassbg: "bg-orange-500",
  signupText: "text-orange-500",
  signupBorder: "border-orange-500",
  lableText: "text-[#F4F4F4]",
  bgbtnColor: "bg-[#FF7315]",
  deleteBg: "bg-[#dc2625]",
};
