import type { Config } from "tailwindcss";
const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./public/assets/**/*.svg",
    "./public/assets/**/*.png",
    "./public/assets/**/*.jpg",
    "./public/assets/**/*.jpeg",
    "./public/assets/**/*.gif",
    "./public/assets/**/*.ico",
  ],

  theme: {
    extend: {
      backgroundImage: {
        "custom-radical": "radial-gradient(circle, black 1px, transparent 2px)",
      },
      backgroundSize: {
        "dotted-size": "20px 20px",
      },
      backdropBlur: {
        backdropBlur: "2px",
      },
      backgroundBlendMode: {
        overlay: "overlay",
      },

      colors: {
        "textInput-color": "#f4f4f4",
        "sunset-primary": "#210062",
        "sunset-background": "#009FBD",
        "sunset-accent": "#77037B",
        "vintageGarden-primary": "#2D4659",
        "vintageGarden-background": "#FDFBDA",
        "vintageGarden-accent": "#819F7F",
        customOrange: "#FF7315",
        vintageGardenPrimary: "#2D4659",
        vintageGardenBackground: "#FDFBDA",
        vintageGardenAccent: "#819F7F",
        cosmicSymphonyPrimary: "#F0EB8D",
        cosmicSymphonyBackground: "#413543",
        cosmicSymphonyAccent: "#8F43EE",
        rusticCharmPrimary: "#EA5455",
        rusticCharmBackground: "#F9F5EB",
        rusticCharmAccent: "#E4BD7D",
        sunsetSerenadePrimary: "#210062",
        sunsetSerenadeBackground: "#009FBD",
        sunsetSerenadeAccent: "#77037B",
        industrialChicPrimary: "#F45050",
        industrialChicBackground: "#F0F0F0",
        industrialChicAccent: "#F9D949",
        blackoutNeutralsPrimary: "#F3EFE0",
        blackoutNeutralsBackground: "#222222",
        blackoutNeutralsAccent: "#22A39F",
        vibrantSpectrumPrimary: "#4A0E5C",
        vibrantSpectrumBackground: "#CCF0C3",
        vibrantSpectrumAccent: "#BCA3CA",
        coastalSunrisePrimary: "#005874",
        coastalSunriseBackground: "#E6E6D4",
        coastalSunriseAccent: "#FFBE00",
        oceanicSerenityPrimary: "#CBE4DE",
        oceanicSerenityBackground: "#2C3333",
        oceanicSerenityAccent: "#2E4F4F",
      },
      fontFamily: {
        "plex-mono": ["IBM Plex Mono"],
        stint: ["Stint_Ultra_Condensed"],
      },
    },
  },
  // safelist: [
  //   "bg-sunset-background",
  //   "bg-sunsetSerenadeBackground",
  //   "text-vintageGarden-primary",
  //   "bg-vintageGardenBackground",
  //   "bg-cosmicSymphonyBackground",
  //   "bg-rusticCharmBackground",
  //   "bg-sunsetSerenadeBackground",
  //   "bg-industrialChicBackground",
  //   "bg-blackoutNeutralsBackground",
  //   "bg-vibrantSpectrumBackground",
  //   "bg-coastalSunriseBackground",
  //   "bg-oceanicSerenityBackground",
  //   "text-vintageGardenPrimary",
  //   "text-cosmicSymphonyPrimary",
  //   "text-rusticCharmPrimary",
  //   "text-sunsetSerenadePrimary",
  //   "text-industrialChicPrimary",
  //   "text-blackoutNeutralsPrimary",
  //   "text-vibrantSpectrumPrimary",
  //   "text-coastalSunrisePrimary",
  //   "text-oceanicSerenityPrimary",
  //   "border-vintageGardenAccent",
  //   "border-cosmicSymphonyAccent",
  //   "border-rusticCharmAccent",
  //   "border-sunsetSerenadeAccent",
  //   "border-industrialChicAccent",
  //   "border-blackoutNeutralsAccent",
  //   "border-vibrantSpectrumAccent",
  //   "border-coastalSunriseAccent",
  //   "border-oceanicSerenityAccent",
  // ],
  plugins: [require("tailwindcss-filters")],
};

export default config;
