import { Theme } from "../../type/type.todo";

export const themes: Theme[] = [
    {
        name: 'Vintage Garden',
        value: 'vintageGarden',
        primary: '#2D4659',
        background: '#FDFBDA',
        accent: '#819F7F',
        textClass: 'text-vintageGardenPrimary',
        bgClass: 'bg-vintageGardenBackground',
        borderClass: 'border-vintageGardenAccent',
    },
    {
        name: 'Cosmic Symphony',
        value: 'cosmicSymphony',
        primary: '#F0EB8D',
        background: '#413543',
        accent: '#8F43EE',
        textClass: 'text-cosmicSymphonyPrimary',
        bgClass: 'bg-cosmicSymphonyBackground',
        borderClass: 'border-cosmicSymphonyAccent',
    },
    {
        name: "Rustic Charm",
        value: "rusticCharm",
        primary: "#EA5455",
        background: "#F9F5EB",
        accent: "#E4BD7D",
        textClass: 'text-rusticCharmPrimary',
        bgClass: 'bg-rusticCharmBackground',
        borderClass: 'border-rusticCharmAccent',
    },
    {
        name: "Sunset Serenade",
        value: "sunsetSerenade",
        primary: "#210062",
        background: "#009FBD",
        accent: "#77037B",
        textClass: 'text-sunsetSerenadePrimary',
        bgClass: 'bg-sunsetSerenadeBackground',
        borderClass: 'border-sunsetSerenadeAccent',
    },
    {
        name: "Industrial Chic",
        value: "industrialChic",
        primary: "#F45050",
        background: "#F0F0F0",
        accent: "#F9D949",
        textClass: 'text-industrialChicPrimary',
        bgClass: 'bg-industrialChicBackground',
        borderClass: 'border-industrialChicAccent',
    },
    {
        name: "Blackout Neutrals",
        value: "blackoutNeutrals",
        primary: "#F3EFE0",
        background: "#222222",
        accent: "#22A39F",
        textClass: 'text-blackoutNeutralsPrimary',
        bgClass: 'bg-blackoutNeutralsBackground',
        borderClass: 'border-blackoutNeutralsAccent',
    },
    {
        name: "Vibrant Spectrum",
        value: "vibrantSpectrum",
        primary: "#4A0E5C",
        background: "#CCF0C3",
        accent: "#BCA3CA",
        textClass: 'text-vibrantSpectrumPrimary',
        bgClass: 'bg-vibrantSpectrumBackground',
        borderClass: 'border-vibrantSpectrumAccent',
    },
    {
        name: "Coastal Sunrise",
        value: "coastalSunrise",
        primary: "#005874",
        background: "#E6E6D4",
        accent: "#FFBE00",
        textClass: 'text-coastalSunrisePrimary',
        bgClass: 'bg-coastalSunriseBackground',
        borderClass: 'border-coastalSunriseAccent',
    },
    {
        name: "Oceanic Serenity",
        value: "oceanicSerenity",
        primary: "#CBE4DE",
        background: "#2C3333",
        accent: "#2E4F4F",
        textClass: 'text-oceanicSerenityPrimary',
        bgClass: 'bg-oceanicSerenityBackground',
        borderClass: 'border-oceanicSerenityAccent',
    }
];